RAW_DATA = {
    "project_title": "Architecting an Autonomous Market Intelligence System",
    "project_subtitle": (
        "Recruiter demo for a provenance-aware real estate intelligence pipeline "
        "covering Newark and Jersey City."
    ),
    "phases": [
        {
            "id": "phase-0",
            "name": "Governance First",
            "status": "implemented-in-demo",
            "summary": "Source registry, legal guardrails, ontology, and confidence tiers.",
        },
        {
            "id": "phase-1",
            "name": "Deterministic Market Map",
            "status": "implemented-in-demo",
            "summary": "Classification, scoring, and corridor-aware prioritization for seeded properties.",
        },
        {
            "id": "phase-2",
            "name": "Ownership Resolution",
            "status": "represented-with-seeded-evidence",
            "summary": "Ownership, lender, and officer claims traced back to demo source documents.",
        },
        {
            "id": "phase-3",
            "name": "Summit Targeting",
            "status": "implemented-in-demo",
            "summary": "People ranking built from property control, civic roles, and prior event overlap.",
        },
    ],
    "relationship_registry": [
        "PARCEL_CONTAINS_BUILDING",
        "BUILDING_HAS_ADDRESS",
        "ORGANIZATION_OWNS_PARCEL",
        "PERSON_IS_OFFICER_OF_ORGANIZATION",
        "FUND_FINANCED_PARCEL",
        "ORGANIZATION_DEVELOPED_PROJECT",
        "PERSON_IS_PRINCIPAL_OF_PROJECT",
        "PERSON_SPOKE_AT_EVENT",
        "ORGANIZATION_SPONSORED_EVENT",
        "PERSON_SERVES_ON_ORGANIZATION",
    ],
    "source_adapters": [
        {
            "source_name": "njgin_parcels",
            "access_method": "bulk_download",
            "mode": "allowed",
            "freshness": "monthly",
            "parser_version": "demo-0.1.0",
            "retention_rules": "cache structured parcel extracts for repeatable scoring runs",
            "rate_limits": "n/a",
            "legal_restrictions": [
                "Owner names are redacted in the public parcel feed.",
                "Use as parcel and assessment foundation only.",
            ],
        },
        {
            "source_name": "overture_buildings",
            "access_method": "bulk_download",
            "mode": "allowed",
            "freshness": "monthly",
            "parser_version": "demo-0.1.0",
            "retention_rules": "cache filtered parquet extracts by market bounding box",
            "rate_limits": "n/a",
            "legal_restrictions": [
                "Use building footprints, addresses, and places as evidence, not as legal ownership.",
            ],
        },
        {
            "source_name": "essex_county_records",
            "access_method": "web_portal",
            "mode": "allowed_with_caveat",
            "freshness": "daily",
            "parser_version": "demo-0.1.0",
            "retention_rules": "retain extracted metadata and source references",
            "rate_limits": "manual pacing required",
            "legal_restrictions": [
                "Portal is informational only and not a replacement for title work.",
            ],
        },
        {
            "source_name": "hudson_county_records",
            "access_method": "web_portal",
            "mode": "allowed",
            "freshness": "daily",
            "parser_version": "demo-0.1.0",
            "retention_rules": "retain document metadata and parsed claims",
            "rate_limits": "manual pacing required",
            "legal_restrictions": [
                "Respect portal rate limits and do not bypass access controls.",
            ],
        },
        {
            "source_name": "google_places_api",
            "access_method": "api",
            "mode": "validation_only",
            "freshness": "live",
            "parser_version": "n/a",
            "retention_rules": "refresh place identifiers within 12 months",
            "rate_limits": "vendor-managed",
            "legal_restrictions": [
                "Do not use for bulk place harvesting or competitor databases.",
            ],
        },
        {
            "source_name": "loopnet_costar",
            "access_method": "web_portal",
            "mode": "manual_only",
            "freshness": "live",
            "parser_version": "n/a",
            "retention_rules": "manual verification only",
            "rate_limits": "n/a",
            "legal_restrictions": [
                "No scraping or automated extraction in the demo or production path.",
            ],
        },
        {
            "source_name": "linkedin",
            "access_method": "web_portal",
            "mode": "manual_or_partner_api",
            "freshness": "live",
            "parser_version": "n/a",
            "retention_rules": "manual or approved API workflows only",
            "rate_limits": "n/a",
            "legal_restrictions": [
                "No scraping. Use official APIs or manual research only.",
            ],
        },
    ],
    "source_documents": [
        {
            "id": "src-njgin-2026-02",
            "source_name": "njgin_parcels",
            "title": "NJGIN statewide parcels extract for Essex and Hudson counties",
            "url": "https://example.com/njgin/parcels/demo",
            "access_date": "2026-02-14",
            "document_type": "bulk_extract",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-overture-2026-02",
            "source_name": "overture_buildings",
            "title": "Overture buildings, addresses, and places demo filter",
            "url": "https://example.com/overture/demo",
            "access_date": "2026-02-14",
            "document_type": "bulk_extract",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-essex-deed-broad",
            "source_name": "essex_county_records",
            "title": "Essex County deed metadata for 110 Broad St",
            "url": "https://example.com/essex/deed/110-broad",
            "access_date": "2026-03-10",
            "document_type": "deed",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-hudson-deed-journal",
            "source_name": "hudson_county_records",
            "title": "Hudson County deed metadata for Journal Square tower site",
            "url": "https://example.com/hudson/deed/journal-square",
            "access_date": "2026-03-09",
            "document_type": "deed",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-njbgs-ironbound",
            "source_name": "nj_business_registry",
            "title": "NJ business entity search for Ironbound Development Partners LLC",
            "url": "https://example.com/njbgs/ironbound",
            "access_date": "2026-03-11",
            "document_type": "entity_registration",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-njbgs-journal",
            "source_name": "nj_business_registry",
            "title": "NJ business entity search for Journal Square Revive LLC",
            "url": "https://example.com/njbgs/journal-square",
            "access_date": "2026-03-11",
            "document_type": "entity_registration",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-mortgage-broad",
            "source_name": "essex_county_records",
            "title": "Mortgage filing for 110 Broad St",
            "url": "https://example.com/essex/mortgage/110-broad",
            "access_date": "2026-03-10",
            "document_type": "mortgage",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-mortgage-journal",
            "source_name": "hudson_county_records",
            "title": "Mortgage filing for Journal Square tower site",
            "url": "https://example.com/hudson/mortgage/journal-square",
            "access_date": "2026-03-09",
            "document_type": "mortgage",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-newark-planning",
            "source_name": "newark_planning_board",
            "title": "Newark planning board agenda mentioning Broad Street modernization",
            "url": "https://example.com/newark/planning/agenda",
            "access_date": "2026-02-28",
            "document_type": "planning_agenda",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-jc-planning",
            "source_name": "jersey_city_planning",
            "title": "Jersey City planning packet for Journal Square tower",
            "url": "https://example.com/jc/planning/packet",
            "access_date": "2026-02-27",
            "document_type": "planning_packet",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-summit-speakers-2025",
            "source_name": "roundtable_internal",
            "title": "Roundtable & Advisory summit speaker roster 2025",
            "url": "https://example.com/internal/summit-speakers",
            "access_date": "2026-03-05",
            "document_type": "event_roster",
            "parser_version": "demo-0.1.0",
        },
        {
            "id": "src-tradepress-jc",
            "source_name": "trade_press",
            "title": "Trade press coverage of Journal Square Revive tower financing",
            "url": "https://example.com/trade-press/journal-square",
            "access_date": "2026-03-01",
            "document_type": "news_article",
            "parser_version": "demo-0.1.0",
        },
    ],
    "corridors": [
        {
            "id": "corr-broad-street",
            "city": "Newark",
            "name": "Broad Street Corridor",
            "importance": 0.95,
        },
        {
            "id": "corr-market-downtown",
            "city": "Newark",
            "name": "Market / Downtown Core",
            "importance": 0.88,
        },
        {
            "id": "corr-journal-square",
            "city": "Jersey City",
            "name": "Journal Square Area",
            "importance": 1.0,
        },
        {
            "id": "corr-grove-street",
            "city": "Jersey City",
            "name": "Grove Street Waterfront",
            "importance": 0.86,
        },
    ],
    "organizations": [
        {
            "id": "org-ironbound-dev",
            "name": "Ironbound Development Partners LLC",
            "category": "developer",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Mendez & Li PC",
            "formation_date": "2018-06-14",
            "in_existing_network": True,
            "city": "Newark",
        },
        {
            "id": "org-newark-education",
            "name": "Newark Education Residences LLC",
            "category": "developer",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Downtown Registered Agents LLC",
            "formation_date": "2016-01-22",
            "in_existing_network": True,
            "city": "Newark",
        },
        {
            "id": "org-portside-industrial",
            "name": "Portside Industrial Holdings LLC",
            "category": "industrial_owner",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Harbor Corporate Services",
            "formation_date": "2019-09-08",
            "in_existing_network": False,
            "city": "Newark",
        },
        {
            "id": "org-journal-square-revive",
            "name": "Journal Square Revive LLC",
            "category": "developer",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Patel Strategic Counsel",
            "formation_date": "2020-03-17",
            "in_existing_network": False,
            "city": "Jersey City",
        },
        {
            "id": "org-grove-residential",
            "name": "Grove Residential Partners LLC",
            "category": "multifamily_owner",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Hudson Filing Services",
            "formation_date": "2017-11-03",
            "in_existing_network": False,
            "city": "Jersey City",
        },
        {
            "id": "org-bergen-arts",
            "name": "Bergen Arts Alliance",
            "category": "nonprofit",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Bergen Arts Alliance",
            "formation_date": "2014-04-20",
            "in_existing_network": True,
            "city": "Jersey City",
        },
        {
            "id": "org-hudson-capital-bank",
            "name": "Hudson Capital Bank",
            "category": "lender",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Corporate Trust Services",
            "formation_date": "1998-02-11",
            "in_existing_network": False,
            "city": "Jersey City",
        },
        {
            "id": "org-garden-state-bank",
            "name": "Garden State Community Bank",
            "category": "lender",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "Corporate Trust Services",
            "formation_date": "2003-08-19",
            "in_existing_network": False,
            "city": "Newark",
        },
        {
            "id": "org-newark-planning-board",
            "name": "Newark Planning Board",
            "category": "government_agency",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "City of Newark",
            "formation_date": "1900-01-01",
            "in_existing_network": True,
            "city": "Newark",
        },
        {
            "id": "org-jc-planning-board",
            "name": "Jersey City Planning Board",
            "category": "government_agency",
            "status": "active",
            "formation_state": "NJ",
            "registered_agent": "City of Jersey City",
            "formation_date": "1900-01-01",
            "in_existing_network": False,
            "city": "Jersey City",
        },
    ],
    "people": [
        {
            "id": "person-samantha-ruiz",
            "name": "Samantha Ruiz",
            "primary_title": "Managing Partner",
            "organization_id": "org-ironbound-dev",
            "email": "sruiz@ironbounddp.com",
            "phone": "(973) 555-0101",
            "city": "Newark",
            "role_type": "developer",
            "in_existing_network": True,
            "prior_speaker": True,
        },
        {
            "id": "person-marcus-bell",
            "name": "Marcus Bell",
            "primary_title": "Principal",
            "organization_id": "org-newark-education",
            "email": "mbell@newarkedures.com",
            "phone": "(973) 555-0124",
            "city": "Newark",
            "role_type": "developer",
            "in_existing_network": True,
            "prior_speaker": False,
        },
        {
            "id": "person-daniel-kim",
            "name": "Daniel Kim",
            "primary_title": "Founder",
            "organization_id": "org-portside-industrial",
            "email": "daniel@portsideholdings.com",
            "phone": "(973) 555-0168",
            "city": "Newark",
            "role_type": "industrial_owner",
            "in_existing_network": False,
            "prior_speaker": False,
        },
        {
            "id": "person-priya-patel",
            "name": "Priya Patel",
            "primary_title": "Managing Director",
            "organization_id": "org-journal-square-revive",
            "email": "ppatel@jsrevive.com",
            "phone": "(201) 555-0154",
            "city": "Jersey City",
            "role_type": "developer",
            "in_existing_network": False,
            "prior_speaker": False,
        },
        {
            "id": "person-lena-ortiz",
            "name": "Lena Ortiz",
            "primary_title": "Principal",
            "organization_id": "org-grove-residential",
            "email": "lortiz@groveresidential.com",
            "phone": "(201) 555-0142",
            "city": "Jersey City",
            "role_type": "multifamily_owner",
            "in_existing_network": False,
            "prior_speaker": False,
        },
        {
            "id": "person-aisha-thompson",
            "name": "Aisha Thompson",
            "primary_title": "Executive Director",
            "organization_id": "org-bergen-arts",
            "email": "athompson@bergenarts.org",
            "phone": "(201) 555-0188",
            "city": "Jersey City",
            "role_type": "nonprofit",
            "in_existing_network": True,
            "prior_speaker": True,
        },
        {
            "id": "person-renee-walker",
            "name": "Renee Walker",
            "primary_title": "Board Liaison",
            "organization_id": "org-newark-planning-board",
            "email": "rwalker@newarknj.gov",
            "phone": "(973) 555-0191",
            "city": "Newark",
            "role_type": "civic",
            "in_existing_network": False,
            "prior_speaker": False,
        },
        {
            "id": "person-victor-chen",
            "name": "Victor Chen",
            "primary_title": "Chair",
            "organization_id": "org-jc-planning-board",
            "email": "vchen@jcnj.org",
            "phone": "(201) 555-0172",
            "city": "Jersey City",
            "role_type": "civic",
            "in_existing_network": False,
            "prior_speaker": False,
        },
        {
            "id": "person-nadia-shah",
            "name": "Nadia Shah",
            "primary_title": "Market Executive",
            "organization_id": "org-hudson-capital-bank",
            "email": "nshah@hudsoncapital.com",
            "phone": "(201) 555-0133",
            "city": "Jersey City",
            "role_type": "capital",
            "in_existing_network": False,
            "prior_speaker": False,
        },
    ],
    "events": [
        {
            "id": "event-newark-summit-2025",
            "name": "Newark Development Summit 2025",
            "date": "2025-10-18",
            "city": "Newark",
            "organizer": "Roundtable & Advisory",
        },
        {
            "id": "event-jc-summit-2025",
            "name": "Jersey City Market Forum 2025",
            "date": "2025-11-12",
            "city": "Jersey City",
            "organizer": "Roundtable & Advisory",
        },
    ],
    "projects": [
        {
            "id": "project-broad-modernization",
            "name": "Broad Street Office Modernization",
            "status": "approved",
            "property_id": "prop-new-001",
            "city": "Newark",
            "description": "Lobby renovation, amenity upgrade, and retail repositioning.",
            "key_date": "2026-04-15",
            "developer_org_id": "org-ironbound-dev",
            "principal_person_id": "person-samantha-ruiz",
            "source_document_id": "src-newark-planning",
        },
        {
            "id": "project-journal-tower",
            "name": "Journal Square Mixed-Use Tower",
            "status": "under_construction",
            "property_id": "prop-jc-001",
            "city": "Jersey City",
            "description": "Office, residential, and retail tower adjacent to PATH access.",
            "key_date": "2026-06-01",
            "developer_org_id": "org-journal-square-revive",
            "principal_person_id": "person-priya-patel",
            "source_document_id": "src-jc-planning",
        },
        {
            "id": "project-bergen-arts-expansion",
            "name": "Bergen Arts Center Expansion",
            "status": "proposed",
            "property_id": "prop-jc-003",
            "city": "Jersey City",
            "description": "Community arts expansion tied to neighborhood revitalization.",
            "key_date": "2026-05-20",
            "developer_org_id": "org-bergen-arts",
            "principal_person_id": "person-aisha-thompson",
            "source_document_id": "src-jc-planning",
        },
    ],
    "properties": [
        {
            "id": "prop-new-001",
            "city": "Newark",
            "name": "110 Broad Street Offices",
            "address": "110 Broad St, Newark, NJ",
            "parcel_pin": "07-1001-00001",
            "block": "1001",
            "lot": "1",
            "county": "Essex",
            "corridor_id": "corr-broad-street",
            "lat": 40.7356,
            "lon": -74.1726,
            "property_class_code": "4A",
            "zoning_code": "MXD",
            "land_value": 10200000,
            "improvement_value": 38400000,
            "building_sqft": 420000,
            "year_built": 1929,
            "transit_distance_m": 180,
            "permit_activity": 0.92,
            "redevelopment_area": True,
            "place_count": 14,
            "known_network_overlap": True,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02", "src-essex-deed-broad"],
        },
        {
            "id": "prop-new-002",
            "city": "Newark",
            "name": "Teachers Village North Block",
            "address": "25 Halsey St, Newark, NJ",
            "parcel_pin": "07-1208-00014",
            "block": "1208",
            "lot": "14",
            "county": "Essex",
            "corridor_id": "corr-market-downtown",
            "lat": 40.7342,
            "lon": -74.1677,
            "property_class_code": "4C",
            "zoning_code": "MX-2",
            "land_value": 6100000,
            "improvement_value": 24100000,
            "building_sqft": 312000,
            "year_built": 2016,
            "transit_distance_m": 120,
            "permit_activity": 0.74,
            "redevelopment_area": True,
            "place_count": 6,
            "known_network_overlap": True,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02"],
        },
        {
            "id": "prop-new-003",
            "city": "Newark",
            "name": "Portside Logistics Hub",
            "address": "450 Frelinghuysen Ave, Newark, NJ",
            "parcel_pin": "07-4101-00009",
            "block": "4101",
            "lot": "9",
            "county": "Essex",
            "corridor_id": "corr-market-downtown",
            "lat": 40.7112,
            "lon": -74.1884,
            "property_class_code": "4B",
            "zoning_code": "I-2",
            "land_value": 5000000,
            "improvement_value": 12400000,
            "building_sqft": 255000,
            "year_built": 1989,
            "transit_distance_m": 650,
            "permit_activity": 0.41,
            "redevelopment_area": False,
            "place_count": 1,
            "known_network_overlap": False,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02"],
        },
        {
            "id": "prop-jc-001",
            "city": "Jersey City",
            "name": "Journal Square Tower Site",
            "address": "532 Summit Ave, Jersey City, NJ",
            "parcel_pin": "09-2501-00003",
            "block": "2501",
            "lot": "3",
            "county": "Hudson",
            "corridor_id": "corr-journal-square",
            "lat": 40.7330,
            "lon": -74.0623,
            "property_class_code": "4A",
            "zoning_code": "MU-H",
            "land_value": 8100000,
            "improvement_value": 34200000,
            "building_sqft": 508000,
            "year_built": 2027,
            "transit_distance_m": 90,
            "permit_activity": 1.0,
            "redevelopment_area": True,
            "place_count": 9,
            "known_network_overlap": False,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02", "src-hudson-deed-journal"],
        },
        {
            "id": "prop-jc-002",
            "city": "Jersey City",
            "name": "Grove Street Multifamily",
            "address": "88 Grove St, Jersey City, NJ",
            "parcel_pin": "09-3104-00012",
            "block": "3104",
            "lot": "12",
            "county": "Hudson",
            "corridor_id": "corr-grove-street",
            "lat": 40.7195,
            "lon": -74.0423,
            "property_class_code": "4C",
            "zoning_code": "R-5",
            "land_value": 4200000,
            "improvement_value": 22300000,
            "building_sqft": 280000,
            "year_built": 2018,
            "transit_distance_m": 220,
            "permit_activity": 0.61,
            "redevelopment_area": False,
            "place_count": 4,
            "known_network_overlap": False,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02"],
        },
        {
            "id": "prop-jc-003",
            "city": "Jersey City",
            "name": "Bergen Public Arts Center",
            "address": "120 Bergen Ave, Jersey City, NJ",
            "parcel_pin": "09-2207-00006",
            "block": "2207",
            "lot": "6",
            "county": "Hudson",
            "corridor_id": "corr-journal-square",
            "lat": 40.7228,
            "lon": -74.0714,
            "property_class_code": "15D",
            "zoning_code": "C-1",
            "land_value": 2300000,
            "improvement_value": 11200000,
            "building_sqft": 98000,
            "year_built": 1951,
            "transit_distance_m": 410,
            "permit_activity": 0.54,
            "redevelopment_area": True,
            "place_count": 2,
            "known_network_overlap": True,
            "source_document_ids": ["src-njgin-2026-02", "src-overture-2026-02", "src-jc-planning"],
        },
    ],
    "ownership_links": [
        {
            "property_id": "prop-new-001",
            "org_id": "org-ironbound-dev",
            "source_document_id": "src-essex-deed-broad",
            "valid_from": "2025-11-18",
            "confidence": "probable",
        },
        {
            "property_id": "prop-new-002",
            "org_id": "org-newark-education",
            "source_document_id": "src-njgin-2026-02",
            "valid_from": "2024-01-01",
            "confidence": "verified",
        },
        {
            "property_id": "prop-new-003",
            "org_id": "org-portside-industrial",
            "source_document_id": "src-njgin-2026-02",
            "valid_from": "2023-08-01",
            "confidence": "verified",
        },
        {
            "property_id": "prop-jc-001",
            "org_id": "org-journal-square-revive",
            "source_document_id": "src-hudson-deed-journal",
            "valid_from": "2026-01-09",
            "confidence": "verified",
        },
        {
            "property_id": "prop-jc-002",
            "org_id": "org-grove-residential",
            "source_document_id": "src-njgin-2026-02",
            "valid_from": "2024-05-17",
            "confidence": "verified",
        },
        {
            "property_id": "prop-jc-003",
            "org_id": "org-bergen-arts",
            "source_document_id": "src-jc-planning",
            "valid_from": "2022-07-01",
            "confidence": "verified",
        },
    ],
    "officer_links": [
        {
            "person_id": "person-samantha-ruiz",
            "org_id": "org-ironbound-dev",
            "title": "Managing Partner",
            "source_document_id": "src-njbgs-ironbound",
            "start_date": "2018-06-14",
            "confidence": "verified",
        },
        {
            "person_id": "person-marcus-bell",
            "org_id": "org-newark-education",
            "title": "Principal",
            "source_document_id": "src-njgin-2026-02",
            "start_date": "2019-01-10",
            "confidence": "verified",
        },
        {
            "person_id": "person-daniel-kim",
            "org_id": "org-portside-industrial",
            "title": "Founder",
            "source_document_id": "src-njgin-2026-02",
            "start_date": "2019-09-08",
            "confidence": "verified",
        },
        {
            "person_id": "person-priya-patel",
            "org_id": "org-journal-square-revive",
            "title": "Managing Director",
            "source_document_id": "src-njbgs-journal",
            "start_date": "2020-03-17",
            "confidence": "verified",
        },
        {
            "person_id": "person-lena-ortiz",
            "org_id": "org-grove-residential",
            "title": "Principal",
            "source_document_id": "src-njgin-2026-02",
            "start_date": "2018-01-01",
            "confidence": "verified",
        },
        {
            "person_id": "person-aisha-thompson",
            "org_id": "org-bergen-arts",
            "title": "Executive Director",
            "source_document_id": "src-jc-planning",
            "start_date": "2021-03-04",
            "confidence": "verified",
        },
        {
            "person_id": "person-renee-walker",
            "org_id": "org-newark-planning-board",
            "title": "Board Liaison",
            "source_document_id": "src-newark-planning",
            "start_date": "2025-01-02",
            "confidence": "verified",
        },
        {
            "person_id": "person-victor-chen",
            "org_id": "org-jc-planning-board",
            "title": "Chair",
            "source_document_id": "src-jc-planning",
            "start_date": "2024-06-11",
            "confidence": "verified",
        },
        {
            "person_id": "person-nadia-shah",
            "org_id": "org-hudson-capital-bank",
            "title": "Market Executive",
            "source_document_id": "src-tradepress-jc",
            "start_date": "2023-09-01",
            "confidence": "probable",
        },
    ],
    "financing_links": [
        {
            "property_id": "prop-new-001",
            "lender_org_id": "org-garden-state-bank",
            "amount": 26500000,
            "recording_date": "2025-11-18",
            "source_document_id": "src-mortgage-broad",
            "confidence": "probable",
        },
        {
            "property_id": "prop-jc-001",
            "lender_org_id": "org-hudson-capital-bank",
            "amount": 39000000,
            "recording_date": "2026-01-09",
            "source_document_id": "src-mortgage-journal",
            "confidence": "verified",
        },
        {
            "property_id": "prop-jc-002",
            "lender_org_id": "org-hudson-capital-bank",
            "amount": 18500000,
            "recording_date": "2024-05-17",
            "source_document_id": "src-mortgage-journal",
            "confidence": "probable",
        },
    ],
    "speaker_links": [
        {
            "person_id": "person-samantha-ruiz",
            "event_id": "event-newark-summit-2025",
            "source_document_id": "src-summit-speakers-2025",
            "confidence": "verified",
        },
        {
            "person_id": "person-aisha-thompson",
            "event_id": "event-jc-summit-2025",
            "source_document_id": "src-summit-speakers-2025",
            "confidence": "verified",
        },
    ],
}
